//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ScireNfes", "nfe_ibfk_1", "fornecedor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Aucom.NFeManifestacao.DAL.fornecedor), "nfe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aucom.NFeManifestacao.DAL.nfe), true)]
[assembly: EdmRelationshipAttribute("ScireNfes", "nfe_dados_ibfk_1", "nfe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Aucom.NFeManifestacao.DAL.nfe), "nfe_dados", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aucom.NFeManifestacao.DAL.nfe_dados), true)]

#endregion

namespace Aucom.NFeManifestacao.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ScireNfeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ScireNfeEntities object using the connection string found in the 'ScireNfeEntities' section of the application configuration file.
        /// </summary>
        public ScireNfeEntities() : base("name=ScireNfeEntities", "ScireNfeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ScireNfeEntities object.
        /// </summary>
        public ScireNfeEntities(string connectionString) : base(connectionString, "ScireNfeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ScireNfeEntities object.
        /// </summary>
        public ScireNfeEntities(EntityConnection connection) : base(connection, "ScireNfeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<destinatario> destinatario
        {
            get
            {
                if ((_destinatario == null))
                {
                    _destinatario = base.CreateObjectSet<destinatario>("destinatario");
                }
                return _destinatario;
            }
        }
        private ObjectSet<destinatario> _destinatario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<fornecedor> fornecedor
        {
            get
            {
                if ((_fornecedor == null))
                {
                    _fornecedor = base.CreateObjectSet<fornecedor>("fornecedor");
                }
                return _fornecedor;
            }
        }
        private ObjectSet<fornecedor> _fornecedor;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<nfe> nfe
        {
            get
            {
                if ((_nfe == null))
                {
                    _nfe = base.CreateObjectSet<nfe>("nfe");
                }
                return _nfe;
            }
        }
        private ObjectSet<nfe> _nfe;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<nfe_dados> nfe_dados
        {
            get
            {
                if ((_nfe_dados == null))
                {
                    _nfe_dados = base.CreateObjectSet<nfe_dados>("nfe_dados");
                }
                return _nfe_dados;
            }
        }
        private ObjectSet<nfe_dados> _nfe_dados;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tipo_evento> tipo_evento
        {
            get
            {
                if ((_tipo_evento == null))
                {
                    _tipo_evento = base.CreateObjectSet<tipo_evento>("tipo_evento");
                }
                return _tipo_evento;
            }
        }
        private ObjectSet<tipo_evento> _tipo_evento;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the destinatario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodestinatario(destinatario destinatario)
        {
            base.AddObject("destinatario", destinatario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the fornecedor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofornecedor(fornecedor fornecedor)
        {
            base.AddObject("fornecedor", fornecedor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the nfe EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonfe(nfe nfe)
        {
            base.AddObject("nfe", nfe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the nfe_dados EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonfe_dados(nfe_dados nfe_dados)
        {
            base.AddObject("nfe_dados", nfe_dados);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tipo_evento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotipo_evento(tipo_evento tipo_evento)
        {
            base.AddObject("tipo_evento", tipo_evento);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="evento">No Metadata Documentation available.</param>
        /// <param name="temxml">No Metadata Documentation available.</param>
        public ObjectResult<stp_NotasUltimoEvento_Result> stp_NotasUltimoEvento(global::System.String evento, Nullable<global::System.SByte> temxml)
        {
            ObjectParameter eventoParameter;
            if (evento != null)
            {
                eventoParameter = new ObjectParameter("evento", evento);
            }
            else
            {
                eventoParameter = new ObjectParameter("evento", typeof(global::System.String));
            }
    
            ObjectParameter temxmlParameter;
            if (temxml.HasValue)
            {
                temxmlParameter = new ObjectParameter("temxml", temxml);
            }
            else
            {
                temxmlParameter = new ObjectParameter("temxml", typeof(global::System.SByte));
            }
    
            return base.ExecuteFunction<stp_NotasUltimoEvento_Result>("stp_NotasUltimoEvento", eventoParameter, temxmlParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ScireNfes", Name="destinatario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class destinatario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new destinatario object.
        /// </summary>
        /// <param name="id_destinatario">Initial value of the id_destinatario property.</param>
        /// <param name="cnpj">Initial value of the cnpj property.</param>
        /// <param name="razao">Initial value of the razao property.</param>
        /// <param name="logradouro">Initial value of the logradouro property.</param>
        /// <param name="numero">Initial value of the numero property.</param>
        /// <param name="complemento">Initial value of the complemento property.</param>
        /// <param name="bairro">Initial value of the bairro property.</param>
        /// <param name="municipio">Initial value of the municipio property.</param>
        /// <param name="uf">Initial value of the uf property.</param>
        /// <param name="cep">Initial value of the cep property.</param>
        /// <param name="pais">Initial value of the pais property.</param>
        /// <param name="fone">Initial value of the fone property.</param>
        /// <param name="ie">Initial value of the ie property.</param>
        public static destinatario Createdestinatario(global::System.Int32 id_destinatario, global::System.String cnpj, global::System.String razao, global::System.String logradouro, global::System.String numero, global::System.String complemento, global::System.String bairro, global::System.String municipio, global::System.String uf, global::System.String cep, global::System.String pais, global::System.String fone, global::System.String ie)
        {
            destinatario destinatario = new destinatario();
            destinatario.id_destinatario = id_destinatario;
            destinatario.cnpj = cnpj;
            destinatario.razao = razao;
            destinatario.logradouro = logradouro;
            destinatario.numero = numero;
            destinatario.complemento = complemento;
            destinatario.bairro = bairro;
            destinatario.municipio = municipio;
            destinatario.uf = uf;
            destinatario.cep = cep;
            destinatario.pais = pais;
            destinatario.fone = fone;
            destinatario.ie = ie;
            return destinatario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_destinatario
        {
            get
            {
                return _id_destinatario;
            }
            set
            {
                if (_id_destinatario != value)
                {
                    Onid_destinatarioChanging(value);
                    ReportPropertyChanging("id_destinatario");
                    _id_destinatario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_destinatario");
                    Onid_destinatarioChanged();
                }
            }
        }
        private global::System.Int32 _id_destinatario;
        partial void Onid_destinatarioChanging(global::System.Int32 value);
        partial void Onid_destinatarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cnpj
        {
            get
            {
                return _cnpj;
            }
            set
            {
                OncnpjChanging(value);
                ReportPropertyChanging("cnpj");
                _cnpj = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cnpj");
                OncnpjChanged();
            }
        }
        private global::System.String _cnpj;
        partial void OncnpjChanging(global::System.String value);
        partial void OncnpjChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String razao
        {
            get
            {
                return _razao;
            }
            set
            {
                OnrazaoChanging(value);
                ReportPropertyChanging("razao");
                _razao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("razao");
                OnrazaoChanged();
            }
        }
        private global::System.String _razao;
        partial void OnrazaoChanging(global::System.String value);
        partial void OnrazaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String logradouro
        {
            get
            {
                return _logradouro;
            }
            set
            {
                OnlogradouroChanging(value);
                ReportPropertyChanging("logradouro");
                _logradouro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("logradouro");
                OnlogradouroChanged();
            }
        }
        private global::System.String _logradouro;
        partial void OnlogradouroChanging(global::System.String value);
        partial void OnlogradouroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private global::System.String _numero;
        partial void OnnumeroChanging(global::System.String value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String complemento
        {
            get
            {
                return _complemento;
            }
            set
            {
                OncomplementoChanging(value);
                ReportPropertyChanging("complemento");
                _complemento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("complemento");
                OncomplementoChanged();
            }
        }
        private global::System.String _complemento;
        partial void OncomplementoChanging(global::System.String value);
        partial void OncomplementoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String bairro
        {
            get
            {
                return _bairro;
            }
            set
            {
                OnbairroChanging(value);
                ReportPropertyChanging("bairro");
                _bairro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("bairro");
                OnbairroChanged();
            }
        }
        private global::System.String _bairro;
        partial void OnbairroChanging(global::System.String value);
        partial void OnbairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String municipio
        {
            get
            {
                return _municipio;
            }
            set
            {
                OnmunicipioChanging(value);
                ReportPropertyChanging("municipio");
                _municipio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("municipio");
                OnmunicipioChanged();
            }
        }
        private global::System.String _municipio;
        partial void OnmunicipioChanging(global::System.String value);
        partial void OnmunicipioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String uf
        {
            get
            {
                return _uf;
            }
            set
            {
                OnufChanging(value);
                ReportPropertyChanging("uf");
                _uf = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("uf");
                OnufChanged();
            }
        }
        private global::System.String _uf;
        partial void OnufChanging(global::System.String value);
        partial void OnufChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cep
        {
            get
            {
                return _cep;
            }
            set
            {
                OncepChanging(value);
                ReportPropertyChanging("cep");
                _cep = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cep");
                OncepChanged();
            }
        }
        private global::System.String _cep;
        partial void OncepChanging(global::System.String value);
        partial void OncepChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pais
        {
            get
            {
                return _pais;
            }
            set
            {
                OnpaisChanging(value);
                ReportPropertyChanging("pais");
                _pais = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pais");
                OnpaisChanged();
            }
        }
        private global::System.String _pais;
        partial void OnpaisChanging(global::System.String value);
        partial void OnpaisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fone
        {
            get
            {
                return _fone;
            }
            set
            {
                OnfoneChanging(value);
                ReportPropertyChanging("fone");
                _fone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fone");
                OnfoneChanged();
            }
        }
        private global::System.String _fone;
        partial void OnfoneChanging(global::System.String value);
        partial void OnfoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ie
        {
            get
            {
                return _ie;
            }
            set
            {
                OnieChanging(value);
                ReportPropertyChanging("ie");
                _ie = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ie");
                OnieChanged();
            }
        }
        private global::System.String _ie;
        partial void OnieChanging(global::System.String value);
        partial void OnieChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ScireNfes", Name="fornecedor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class fornecedor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new fornecedor object.
        /// </summary>
        /// <param name="id_fornecedor">Initial value of the id_fornecedor property.</param>
        /// <param name="cnpj">Initial value of the cnpj property.</param>
        /// <param name="razao">Initial value of the razao property.</param>
        /// <param name="logradouro">Initial value of the logradouro property.</param>
        /// <param name="numero">Initial value of the numero property.</param>
        /// <param name="complemento">Initial value of the complemento property.</param>
        /// <param name="bairro">Initial value of the bairro property.</param>
        /// <param name="municipio">Initial value of the municipio property.</param>
        /// <param name="uf">Initial value of the uf property.</param>
        /// <param name="cep">Initial value of the cep property.</param>
        /// <param name="pais">Initial value of the pais property.</param>
        /// <param name="fone">Initial value of the fone property.</param>
        /// <param name="ie">Initial value of the ie property.</param>
        /// <param name="im">Initial value of the im property.</param>
        /// <param name="cnae">Initial value of the cnae property.</param>
        /// <param name="crt">Initial value of the crt property.</param>
        public static fornecedor Createfornecedor(global::System.Int32 id_fornecedor, global::System.String cnpj, global::System.String razao, global::System.String logradouro, global::System.String numero, global::System.String complemento, global::System.String bairro, global::System.String municipio, global::System.String uf, global::System.String cep, global::System.String pais, global::System.String fone, global::System.String ie, global::System.String im, global::System.String cnae, global::System.String crt)
        {
            fornecedor fornecedor = new fornecedor();
            fornecedor.id_fornecedor = id_fornecedor;
            fornecedor.cnpj = cnpj;
            fornecedor.razao = razao;
            fornecedor.logradouro = logradouro;
            fornecedor.numero = numero;
            fornecedor.complemento = complemento;
            fornecedor.bairro = bairro;
            fornecedor.municipio = municipio;
            fornecedor.uf = uf;
            fornecedor.cep = cep;
            fornecedor.pais = pais;
            fornecedor.fone = fone;
            fornecedor.ie = ie;
            fornecedor.im = im;
            fornecedor.cnae = cnae;
            fornecedor.crt = crt;
            return fornecedor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_fornecedor
        {
            get
            {
                return _id_fornecedor;
            }
            set
            {
                if (_id_fornecedor != value)
                {
                    Onid_fornecedorChanging(value);
                    ReportPropertyChanging("id_fornecedor");
                    _id_fornecedor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_fornecedor");
                    Onid_fornecedorChanged();
                }
            }
        }
        private global::System.Int32 _id_fornecedor;
        partial void Onid_fornecedorChanging(global::System.Int32 value);
        partial void Onid_fornecedorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cnpj
        {
            get
            {
                return _cnpj;
            }
            set
            {
                OncnpjChanging(value);
                ReportPropertyChanging("cnpj");
                _cnpj = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cnpj");
                OncnpjChanged();
            }
        }
        private global::System.String _cnpj;
        partial void OncnpjChanging(global::System.String value);
        partial void OncnpjChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String razao
        {
            get
            {
                return _razao;
            }
            set
            {
                OnrazaoChanging(value);
                ReportPropertyChanging("razao");
                _razao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("razao");
                OnrazaoChanged();
            }
        }
        private global::System.String _razao;
        partial void OnrazaoChanging(global::System.String value);
        partial void OnrazaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String logradouro
        {
            get
            {
                return _logradouro;
            }
            set
            {
                OnlogradouroChanging(value);
                ReportPropertyChanging("logradouro");
                _logradouro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("logradouro");
                OnlogradouroChanged();
            }
        }
        private global::System.String _logradouro;
        partial void OnlogradouroChanging(global::System.String value);
        partial void OnlogradouroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private global::System.String _numero;
        partial void OnnumeroChanging(global::System.String value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String complemento
        {
            get
            {
                return _complemento;
            }
            set
            {
                OncomplementoChanging(value);
                ReportPropertyChanging("complemento");
                _complemento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("complemento");
                OncomplementoChanged();
            }
        }
        private global::System.String _complemento;
        partial void OncomplementoChanging(global::System.String value);
        partial void OncomplementoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String bairro
        {
            get
            {
                return _bairro;
            }
            set
            {
                OnbairroChanging(value);
                ReportPropertyChanging("bairro");
                _bairro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("bairro");
                OnbairroChanged();
            }
        }
        private global::System.String _bairro;
        partial void OnbairroChanging(global::System.String value);
        partial void OnbairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String municipio
        {
            get
            {
                return _municipio;
            }
            set
            {
                OnmunicipioChanging(value);
                ReportPropertyChanging("municipio");
                _municipio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("municipio");
                OnmunicipioChanged();
            }
        }
        private global::System.String _municipio;
        partial void OnmunicipioChanging(global::System.String value);
        partial void OnmunicipioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String uf
        {
            get
            {
                return _uf;
            }
            set
            {
                OnufChanging(value);
                ReportPropertyChanging("uf");
                _uf = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("uf");
                OnufChanged();
            }
        }
        private global::System.String _uf;
        partial void OnufChanging(global::System.String value);
        partial void OnufChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cep
        {
            get
            {
                return _cep;
            }
            set
            {
                OncepChanging(value);
                ReportPropertyChanging("cep");
                _cep = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cep");
                OncepChanged();
            }
        }
        private global::System.String _cep;
        partial void OncepChanging(global::System.String value);
        partial void OncepChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pais
        {
            get
            {
                return _pais;
            }
            set
            {
                OnpaisChanging(value);
                ReportPropertyChanging("pais");
                _pais = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pais");
                OnpaisChanged();
            }
        }
        private global::System.String _pais;
        partial void OnpaisChanging(global::System.String value);
        partial void OnpaisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fone
        {
            get
            {
                return _fone;
            }
            set
            {
                OnfoneChanging(value);
                ReportPropertyChanging("fone");
                _fone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fone");
                OnfoneChanged();
            }
        }
        private global::System.String _fone;
        partial void OnfoneChanging(global::System.String value);
        partial void OnfoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ie
        {
            get
            {
                return _ie;
            }
            set
            {
                OnieChanging(value);
                ReportPropertyChanging("ie");
                _ie = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ie");
                OnieChanged();
            }
        }
        private global::System.String _ie;
        partial void OnieChanging(global::System.String value);
        partial void OnieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String im
        {
            get
            {
                return _im;
            }
            set
            {
                OnimChanging(value);
                ReportPropertyChanging("im");
                _im = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("im");
                OnimChanged();
            }
        }
        private global::System.String _im;
        partial void OnimChanging(global::System.String value);
        partial void OnimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cnae
        {
            get
            {
                return _cnae;
            }
            set
            {
                OncnaeChanging(value);
                ReportPropertyChanging("cnae");
                _cnae = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cnae");
                OncnaeChanged();
            }
        }
        private global::System.String _cnae;
        partial void OncnaeChanging(global::System.String value);
        partial void OncnaeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String crt
        {
            get
            {
                return _crt;
            }
            set
            {
                OncrtChanging(value);
                ReportPropertyChanging("crt");
                _crt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("crt");
                OncrtChanged();
            }
        }
        private global::System.String _crt;
        partial void OncrtChanging(global::System.String value);
        partial void OncrtChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScireNfes", "nfe_ibfk_1", "nfe")]
        public EntityCollection<nfe> nfe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<nfe>("ScireNfes.nfe_ibfk_1", "nfe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<nfe>("ScireNfes.nfe_ibfk_1", "nfe", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ScireNfes", Name="nfe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class nfe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new nfe object.
        /// </summary>
        /// <param name="id_nfe">Initial value of the id_nfe property.</param>
        /// <param name="chave">Initial value of the chave property.</param>
        /// <param name="fornecedor">Initial value of the fornecedor property.</param>
        /// <param name="data_hora">Initial value of the data_hora property.</param>
        public static nfe Createnfe(global::System.Int32 id_nfe, global::System.String chave, global::System.Int32 fornecedor, global::System.DateTime data_hora)
        {
            nfe nfe = new nfe();
            nfe.id_nfe = id_nfe;
            nfe.chave = chave;
            nfe.fornecedor = fornecedor;
            nfe.data_hora = data_hora;
            return nfe;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_nfe
        {
            get
            {
                return _id_nfe;
            }
            set
            {
                if (_id_nfe != value)
                {
                    Onid_nfeChanging(value);
                    ReportPropertyChanging("id_nfe");
                    _id_nfe = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_nfe");
                    Onid_nfeChanged();
                }
            }
        }
        private global::System.Int32 _id_nfe;
        partial void Onid_nfeChanging(global::System.Int32 value);
        partial void Onid_nfeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String chave
        {
            get
            {
                return _chave;
            }
            set
            {
                OnchaveChanging(value);
                ReportPropertyChanging("chave");
                _chave = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("chave");
                OnchaveChanged();
            }
        }
        private global::System.String _chave;
        partial void OnchaveChanging(global::System.String value);
        partial void OnchaveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String destinatario
        {
            get
            {
                return _destinatario;
            }
            set
            {
                OndestinatarioChanging(value);
                ReportPropertyChanging("destinatario");
                _destinatario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("destinatario");
                OndestinatarioChanged();
            }
        }
        private global::System.String _destinatario;
        partial void OndestinatarioChanging(global::System.String value);
        partial void OndestinatarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fornecedor
        {
            get
            {
                return _fornecedor;
            }
            set
            {
                OnfornecedorChanging(value);
                ReportPropertyChanging("fornecedor");
                _fornecedor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fornecedor");
                OnfornecedorChanged();
            }
        }
        private global::System.Int32 _fornecedor;
        partial void OnfornecedorChanging(global::System.Int32 value);
        partial void OnfornecedorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data_hora
        {
            get
            {
                return _data_hora;
            }
            set
            {
                Ondata_horaChanging(value);
                ReportPropertyChanging("data_hora");
                _data_hora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_hora");
                Ondata_horaChanged();
            }
        }
        private global::System.DateTime _data_hora;
        partial void Ondata_horaChanging(global::System.DateTime value);
        partial void Ondata_horaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> valor_total
        {
            get
            {
                return _valor_total;
            }
            set
            {
                Onvalor_totalChanging(value);
                ReportPropertyChanging("valor_total");
                _valor_total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor_total");
                Onvalor_totalChanged();
            }
        }
        private Nullable<global::System.Double> _valor_total;
        partial void Onvalor_totalChanging(Nullable<global::System.Double> value);
        partial void Onvalor_totalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String xml_nfe
        {
            get
            {
                return _xml_nfe;
            }
            set
            {
                Onxml_nfeChanging(value);
                ReportPropertyChanging("xml_nfe");
                _xml_nfe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("xml_nfe");
                Onxml_nfeChanged();
            }
        }
        private global::System.String _xml_nfe;
        partial void Onxml_nfeChanging(global::System.String value);
        partial void Onxml_nfeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScireNfes", "nfe_ibfk_1", "fornecedor")]
        public fornecedor fornecedor1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<fornecedor>("ScireNfes.nfe_ibfk_1", "fornecedor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<fornecedor>("ScireNfes.nfe_ibfk_1", "fornecedor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<fornecedor> fornecedor1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<fornecedor>("ScireNfes.nfe_ibfk_1", "fornecedor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<fornecedor>("ScireNfes.nfe_ibfk_1", "fornecedor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScireNfes", "nfe_dados_ibfk_1", "nfe_dados")]
        public EntityCollection<nfe_dados> nfe_dados
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<nfe_dados>("ScireNfes.nfe_dados_ibfk_1", "nfe_dados");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<nfe_dados>("ScireNfes.nfe_dados_ibfk_1", "nfe_dados", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ScireNfes", Name="nfe_dados")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class nfe_dados : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new nfe_dados object.
        /// </summary>
        /// <param name="id_nfe_dados">Initial value of the id_nfe_dados property.</param>
        /// <param name="nfe">Initial value of the nfe property.</param>
        /// <param name="operacao">Initial value of the operacao property.</param>
        /// <param name="protocolo">Initial value of the protocolo property.</param>
        /// <param name="tipo">Initial value of the tipo property.</param>
        /// <param name="data_sefaz">Initial value of the data_sefaz property.</param>
        /// <param name="data_sistema">Initial value of the data_sistema property.</param>
        /// <param name="xml">Initial value of the xml property.</param>
        public static nfe_dados Createnfe_dados(global::System.Int32 id_nfe_dados, global::System.Int32 nfe, global::System.String operacao, global::System.String protocolo, global::System.String tipo, global::System.DateTime data_sefaz, global::System.DateTime data_sistema, global::System.String xml)
        {
            nfe_dados nfe_dados = new nfe_dados();
            nfe_dados.id_nfe_dados = id_nfe_dados;
            nfe_dados.nfe = nfe;
            nfe_dados.operacao = operacao;
            nfe_dados.protocolo = protocolo;
            nfe_dados.tipo = tipo;
            nfe_dados.data_sefaz = data_sefaz;
            nfe_dados.data_sistema = data_sistema;
            nfe_dados.xml = xml;
            return nfe_dados;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_nfe_dados
        {
            get
            {
                return _id_nfe_dados;
            }
            set
            {
                if (_id_nfe_dados != value)
                {
                    Onid_nfe_dadosChanging(value);
                    ReportPropertyChanging("id_nfe_dados");
                    _id_nfe_dados = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_nfe_dados");
                    Onid_nfe_dadosChanged();
                }
            }
        }
        private global::System.Int32 _id_nfe_dados;
        partial void Onid_nfe_dadosChanging(global::System.Int32 value);
        partial void Onid_nfe_dadosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nfe
        {
            get
            {
                return _nfe;
            }
            set
            {
                OnnfeChanging(value);
                ReportPropertyChanging("nfe");
                _nfe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nfe");
                OnnfeChanged();
            }
        }
        private global::System.Int32 _nfe;
        partial void OnnfeChanging(global::System.Int32 value);
        partial void OnnfeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String operacao
        {
            get
            {
                return _operacao;
            }
            set
            {
                OnoperacaoChanging(value);
                ReportPropertyChanging("operacao");
                _operacao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("operacao");
                OnoperacaoChanged();
            }
        }
        private global::System.String _operacao;
        partial void OnoperacaoChanging(global::System.String value);
        partial void OnoperacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String protocolo
        {
            get
            {
                return _protocolo;
            }
            set
            {
                OnprotocoloChanging(value);
                ReportPropertyChanging("protocolo");
                _protocolo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("protocolo");
                OnprotocoloChanged();
            }
        }
        private global::System.String _protocolo;
        partial void OnprotocoloChanging(global::System.String value);
        partial void OnprotocoloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                OncodigoChanging(value);
                ReportPropertyChanging("codigo");
                _codigo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("codigo");
                OncodigoChanged();
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data_sefaz
        {
            get
            {
                return _data_sefaz;
            }
            set
            {
                Ondata_sefazChanging(value);
                ReportPropertyChanging("data_sefaz");
                _data_sefaz = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_sefaz");
                Ondata_sefazChanged();
            }
        }
        private global::System.DateTime _data_sefaz;
        partial void Ondata_sefazChanging(global::System.DateTime value);
        partial void Ondata_sefazChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data_sistema
        {
            get
            {
                return _data_sistema;
            }
            set
            {
                Ondata_sistemaChanging(value);
                ReportPropertyChanging("data_sistema");
                _data_sistema = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_sistema");
                Ondata_sistemaChanged();
            }
        }
        private global::System.DateTime _data_sistema;
        partial void Ondata_sistemaChanging(global::System.DateTime value);
        partial void Ondata_sistemaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String xml
        {
            get
            {
                return _xml;
            }
            set
            {
                OnxmlChanging(value);
                ReportPropertyChanging("xml");
                _xml = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("xml");
                OnxmlChanged();
            }
        }
        private global::System.String _xml;
        partial void OnxmlChanging(global::System.String value);
        partial void OnxmlChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ScireNfes", "nfe_dados_ibfk_1", "nfe")]
        public nfe nfe1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<nfe>("ScireNfes.nfe_dados_ibfk_1", "nfe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<nfe>("ScireNfes.nfe_dados_ibfk_1", "nfe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<nfe> nfe1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<nfe>("ScireNfes.nfe_dados_ibfk_1", "nfe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<nfe>("ScireNfes.nfe_dados_ibfk_1", "nfe", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ScireNfes", Name="tipo_evento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tipo_evento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tipo_evento object.
        /// </summary>
        /// <param name="id_tipo">Initial value of the id_tipo property.</param>
        /// <param name="tipo">Initial value of the tipo property.</param>
        /// <param name="just">Initial value of the just property.</param>
        public static tipo_evento Createtipo_evento(global::System.Int32 id_tipo, global::System.String tipo, global::System.Boolean just)
        {
            tipo_evento tipo_evento = new tipo_evento();
            tipo_evento.id_tipo = id_tipo;
            tipo_evento.tipo = tipo;
            tipo_evento.just = just;
            return tipo_evento;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_tipo
        {
            get
            {
                return _id_tipo;
            }
            set
            {
                if (_id_tipo != value)
                {
                    Onid_tipoChanging(value);
                    ReportPropertyChanging("id_tipo");
                    _id_tipo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_tipo");
                    Onid_tipoChanged();
                }
            }
        }
        private global::System.Int32 _id_tipo;
        partial void Onid_tipoChanging(global::System.Int32 value);
        partial void Onid_tipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean just
        {
            get
            {
                return _just;
            }
            set
            {
                OnjustChanging(value);
                ReportPropertyChanging("just");
                _just = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("just");
                OnjustChanged();
            }
        }
        private global::System.Boolean _just;
        partial void OnjustChanging(global::System.Boolean value);
        partial void OnjustChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ScireNfes", Name="stp_NotasUltimoEvento_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class stp_NotasUltimoEvento_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new stp_NotasUltimoEvento_Result object.
        /// </summary>
        /// <param name="chave">Initial value of the chave property.</param>
        public static stp_NotasUltimoEvento_Result Createstp_NotasUltimoEvento_Result(global::System.String chave)
        {
            stp_NotasUltimoEvento_Result stp_NotasUltimoEvento_Result = new stp_NotasUltimoEvento_Result();
            stp_NotasUltimoEvento_Result.chave = chave;
            return stp_NotasUltimoEvento_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String chave
        {
            get
            {
                return _chave;
            }
            set
            {
                OnchaveChanging(value);
                ReportPropertyChanging("chave");
                _chave = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("chave");
                OnchaveChanged();
            }
        }
        private global::System.String _chave;
        partial void OnchaveChanging(global::System.String value);
        partial void OnchaveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String xml_nfe
        {
            get
            {
                return _xml_nfe;
            }
            set
            {
                Onxml_nfeChanging(value);
                ReportPropertyChanging("xml_nfe");
                _xml_nfe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("xml_nfe");
                Onxml_nfeChanged();
            }
        }
        private global::System.String _xml_nfe;
        partial void Onxml_nfeChanging(global::System.String value);
        partial void Onxml_nfeChanged();

        #endregion

    }

    #endregion

    
}
