//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ManifestaModel", "nfe_ibfk_2", "situacao_nfe", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Aucom.NFeManifestacao.DAL.situacao_nfe), "nfe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aucom.NFeManifestacao.DAL.nfe), true)]
[assembly: EdmRelationshipAttribute("ManifestaModel", "nfe_evento_ibfk_2", "tipo_evento", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Aucom.NFeManifestacao.DAL.tipo_evento), "nfe_evento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Aucom.NFeManifestacao.DAL.nfe_evento), true)]

#endregion

namespace Aucom.NFeManifestacao.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class manifestaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new manifestaEntities object using the connection string found in the 'manifestaEntities' section of the application configuration file.
        /// </summary>
        public manifestaEntities() : base("name=manifestaEntities", "manifestaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new manifestaEntities object.
        /// </summary>
        public manifestaEntities(string connectionString) : base(connectionString, "manifestaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new manifestaEntities object.
        /// </summary>
        public manifestaEntities(EntityConnection connection) : base(connection, "manifestaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<uptabelas> uptabelas
        {
            get
            {
                if ((_uptabelas == null))
                {
                    _uptabelas = base.CreateObjectSet<uptabelas>("uptabelas");
                }
                return _uptabelas;
            }
        }
        private ObjectSet<uptabelas> _uptabelas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<nfe> nfe
        {
            get
            {
                if ((_nfe == null))
                {
                    _nfe = base.CreateObjectSet<nfe>("nfe");
                }
                return _nfe;
            }
        }
        private ObjectSet<nfe> _nfe;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<nfe_evento> nfe_evento
        {
            get
            {
                if ((_nfe_evento == null))
                {
                    _nfe_evento = base.CreateObjectSet<nfe_evento>("nfe_evento");
                }
                return _nfe_evento;
            }
        }
        private ObjectSet<nfe_evento> _nfe_evento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<nfe_fornecedor> nfe_fornecedor
        {
            get
            {
                if ((_nfe_fornecedor == null))
                {
                    _nfe_fornecedor = base.CreateObjectSet<nfe_fornecedor>("nfe_fornecedor");
                }
                return _nfe_fornecedor;
            }
        }
        private ObjectSet<nfe_fornecedor> _nfe_fornecedor;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<situacao_nfe> situacao_nfe
        {
            get
            {
                if ((_situacao_nfe == null))
                {
                    _situacao_nfe = base.CreateObjectSet<situacao_nfe>("situacao_nfe");
                }
                return _situacao_nfe;
            }
        }
        private ObjectSet<situacao_nfe> _situacao_nfe;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tipo_evento> tipo_evento
        {
            get
            {
                if ((_tipo_evento == null))
                {
                    _tipo_evento = base.CreateObjectSet<tipo_evento>("tipo_evento");
                }
                return _tipo_evento;
            }
        }
        private ObjectSet<tipo_evento> _tipo_evento;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the uptabelas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouptabelas(uptabelas uptabelas)
        {
            base.AddObject("uptabelas", uptabelas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the nfe EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonfe(nfe nfe)
        {
            base.AddObject("nfe", nfe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the nfe_evento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonfe_evento(nfe_evento nfe_evento)
        {
            base.AddObject("nfe_evento", nfe_evento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the nfe_fornecedor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonfe_fornecedor(nfe_fornecedor nfe_fornecedor)
        {
            base.AddObject("nfe_fornecedor", nfe_fornecedor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the situacao_nfe EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosituacao_nfe(situacao_nfe situacao_nfe)
        {
            base.AddObject("situacao_nfe", situacao_nfe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tipo_evento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotipo_evento(tipo_evento tipo_evento)
        {
            base.AddObject("tipo_evento", tipo_evento);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ManifestaModel", Name="nfe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class nfe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new nfe object.
        /// </summary>
        /// <param name="chave">Initial value of the chave property.</param>
        /// <param name="fornecedor">Initial value of the fornecedor property.</param>
        public static nfe Createnfe(global::System.String chave, global::System.String fornecedor)
        {
            nfe nfe = new nfe();
            nfe.chave = chave;
            nfe.fornecedor = fornecedor;
            return nfe;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String chave
        {
            get
            {
                return _chave;
            }
            set
            {
                if (_chave != value)
                {
                    OnchaveChanging(value);
                    ReportPropertyChanging("chave");
                    _chave = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("chave");
                    OnchaveChanged();
                }
            }
        }
        private global::System.String _chave;
        partial void OnchaveChanging(global::System.String value);
        partial void OnchaveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fornecedor
        {
            get
            {
                return _fornecedor;
            }
            set
            {
                if (_fornecedor != value)
                {
                    OnfornecedorChanging(value);
                    ReportPropertyChanging("fornecedor");
                    _fornecedor = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("fornecedor");
                    OnfornecedorChanged();
                }
            }
        }
        private global::System.String _fornecedor;
        partial void OnfornecedorChanging(global::System.String value);
        partial void OnfornecedorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> valorTotal
        {
            get
            {
                return _valorTotal;
            }
            set
            {
                OnvalorTotalChanging(value);
                ReportPropertyChanging("valorTotal");
                _valorTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valorTotal");
                OnvalorTotalChanged();
            }
        }
        private Nullable<global::System.Double> _valorTotal;
        partial void OnvalorTotalChanging(Nullable<global::System.Double> value);
        partial void OnvalorTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dataAutorizada
        {
            get
            {
                return _dataAutorizada;
            }
            set
            {
                OndataAutorizadaChanging(value);
                ReportPropertyChanging("dataAutorizada");
                _dataAutorizada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataAutorizada");
                OndataAutorizadaChanged();
            }
        }
        private Nullable<global::System.DateTime> _dataAutorizada;
        partial void OndataAutorizadaChanging(Nullable<global::System.DateTime> value);
        partial void OndataAutorizadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> protocolo
        {
            get
            {
                return _protocolo;
            }
            set
            {
                OnprotocoloChanging(value);
                ReportPropertyChanging("protocolo");
                _protocolo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("protocolo");
                OnprotocoloChanged();
            }
        }
        private Nullable<global::System.Int64> _protocolo;
        partial void OnprotocoloChanging(Nullable<global::System.Int64> value);
        partial void OnprotocoloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> situacao
        {
            get
            {
                return _situacao;
            }
            set
            {
                OnsituacaoChanging(value);
                ReportPropertyChanging("situacao");
                _situacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("situacao");
                OnsituacaoChanged();
            }
        }
        private Nullable<global::System.Int32> _situacao;
        partial void OnsituacaoChanging(Nullable<global::System.Int32> value);
        partial void OnsituacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UF
        {
            get
            {
                return _UF;
            }
            set
            {
                OnUFChanging(value);
                ReportPropertyChanging("UF");
                _UF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UF");
                OnUFChanged();
            }
        }
        private global::System.String _UF;
        partial void OnUFChanging(global::System.String value);
        partial void OnUFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nfeXml
        {
            get
            {
                return _nfeXml;
            }
            set
            {
                OnnfeXmlChanging(value);
                ReportPropertyChanging("nfeXml");
                _nfeXml = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nfeXml");
                OnnfeXmlChanged();
            }
        }
        private global::System.String _nfeXml;
        partial void OnnfeXmlChanging(global::System.String value);
        partial void OnnfeXmlChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ManifestaModel", "nfe_ibfk_2", "situacao_nfe")]
        public situacao_nfe situacao_nfe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<situacao_nfe>("ManifestaModel.nfe_ibfk_2", "situacao_nfe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<situacao_nfe>("ManifestaModel.nfe_ibfk_2", "situacao_nfe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<situacao_nfe> situacao_nfeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<situacao_nfe>("ManifestaModel.nfe_ibfk_2", "situacao_nfe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<situacao_nfe>("ManifestaModel.nfe_ibfk_2", "situacao_nfe", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ManifestaModel", Name="nfe_evento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class nfe_evento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new nfe_evento object.
        /// </summary>
        /// <param name="chave">Initial value of the chave property.</param>
        /// <param name="dataEvento">Initial value of the dataEvento property.</param>
        public static nfe_evento Createnfe_evento(global::System.String chave, global::System.DateTime dataEvento)
        {
            nfe_evento nfe_evento = new nfe_evento();
            nfe_evento.chave = chave;
            nfe_evento.dataEvento = dataEvento;
            return nfe_evento;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String chave
        {
            get
            {
                return _chave;
            }
            set
            {
                if (_chave != value)
                {
                    OnchaveChanging(value);
                    ReportPropertyChanging("chave");
                    _chave = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("chave");
                    OnchaveChanged();
                }
            }
        }
        private global::System.String _chave;
        partial void OnchaveChanging(global::System.String value);
        partial void OnchaveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> lote
        {
            get
            {
                return _lote;
            }
            set
            {
                OnloteChanging(value);
                ReportPropertyChanging("lote");
                _lote = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lote");
                OnloteChanged();
            }
        }
        private Nullable<global::System.Int32> _lote;
        partial void OnloteChanging(Nullable<global::System.Int32> value);
        partial void OnloteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String motivo
        {
            get
            {
                return _motivo;
            }
            set
            {
                OnmotivoChanging(value);
                ReportPropertyChanging("motivo");
                _motivo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("motivo");
                OnmotivoChanged();
            }
        }
        private global::System.String _motivo;
        partial void OnmotivoChanging(global::System.String value);
        partial void OnmotivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dataEvento
        {
            get
            {
                return _dataEvento;
            }
            set
            {
                OndataEventoChanging(value);
                ReportPropertyChanging("dataEvento");
                _dataEvento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataEvento");
                OndataEventoChanged();
            }
        }
        private global::System.DateTime _dataEvento;
        partial void OndataEventoChanging(global::System.DateTime value);
        partial void OndataEventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> protocolo
        {
            get
            {
                return _protocolo;
            }
            set
            {
                OnprotocoloChanging(value);
                ReportPropertyChanging("protocolo");
                _protocolo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("protocolo");
                OnprotocoloChanged();
            }
        }
        private Nullable<global::System.Int64> _protocolo;
        partial void OnprotocoloChanging(Nullable<global::System.Int64> value);
        partial void OnprotocoloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String resposta
        {
            get
            {
                return _resposta;
            }
            set
            {
                OnrespostaChanging(value);
                ReportPropertyChanging("resposta");
                _resposta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("resposta");
                OnrespostaChanged();
            }
        }
        private global::System.String _resposta;
        partial void OnrespostaChanging(global::System.String value);
        partial void OnrespostaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tipoEvento
        {
            get
            {
                return _tipoEvento;
            }
            set
            {
                OntipoEventoChanging(value);
                ReportPropertyChanging("tipoEvento");
                _tipoEvento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipoEvento");
                OntipoEventoChanged();
            }
        }
        private Nullable<global::System.Int32> _tipoEvento;
        partial void OntipoEventoChanging(Nullable<global::System.Int32> value);
        partial void OntipoEventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UF
        {
            get
            {
                return _UF;
            }
            set
            {
                OnUFChanging(value);
                ReportPropertyChanging("UF");
                _UF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UF");
                OnUFChanged();
            }
        }
        private global::System.String _UF;
        partial void OnUFChanging(global::System.String value);
        partial void OnUFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eventoXml
        {
            get
            {
                return _eventoXml;
            }
            set
            {
                OneventoXmlChanging(value);
                ReportPropertyChanging("eventoXml");
                _eventoXml = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eventoXml");
                OneventoXmlChanged();
            }
        }
        private global::System.String _eventoXml;
        partial void OneventoXmlChanging(global::System.String value);
        partial void OneventoXmlChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ManifestaModel", "nfe_evento_ibfk_2", "tipo_evento")]
        public tipo_evento tipo_evento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo_evento>("ManifestaModel.nfe_evento_ibfk_2", "tipo_evento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo_evento>("ManifestaModel.nfe_evento_ibfk_2", "tipo_evento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tipo_evento> tipo_eventoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo_evento>("ManifestaModel.nfe_evento_ibfk_2", "tipo_evento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tipo_evento>("ManifestaModel.nfe_evento_ibfk_2", "tipo_evento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ManifestaModel", Name="nfe_fornecedor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class nfe_fornecedor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new nfe_fornecedor object.
        /// </summary>
        /// <param name="documento">Initial value of the documento property.</param>
        /// <param name="razao">Initial value of the razao property.</param>
        /// <param name="ie">Initial value of the ie property.</param>
        public static nfe_fornecedor Createnfe_fornecedor(global::System.String documento, global::System.String razao, global::System.String ie)
        {
            nfe_fornecedor nfe_fornecedor = new nfe_fornecedor();
            nfe_fornecedor.documento = documento;
            nfe_fornecedor.razao = razao;
            nfe_fornecedor.ie = ie;
            return nfe_fornecedor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String documento
        {
            get
            {
                return _documento;
            }
            set
            {
                if (_documento != value)
                {
                    OndocumentoChanging(value);
                    ReportPropertyChanging("documento");
                    _documento = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("documento");
                    OndocumentoChanged();
                }
            }
        }
        private global::System.String _documento;
        partial void OndocumentoChanging(global::System.String value);
        partial void OndocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String razao
        {
            get
            {
                return _razao;
            }
            set
            {
                if (_razao != value)
                {
                    OnrazaoChanging(value);
                    ReportPropertyChanging("razao");
                    _razao = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("razao");
                    OnrazaoChanged();
                }
            }
        }
        private global::System.String _razao;
        partial void OnrazaoChanging(global::System.String value);
        partial void OnrazaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ie
        {
            get
            {
                return _ie;
            }
            set
            {
                OnieChanging(value);
                ReportPropertyChanging("ie");
                _ie = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ie");
                OnieChanged();
            }
        }
        private global::System.String _ie;
        partial void OnieChanging(global::System.String value);
        partial void OnieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dataCadastro
        {
            get
            {
                return _dataCadastro;
            }
            set
            {
                OndataCadastroChanging(value);
                ReportPropertyChanging("dataCadastro");
                _dataCadastro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataCadastro");
                OndataCadastroChanged();
            }
        }
        private Nullable<global::System.DateTime> _dataCadastro;
        partial void OndataCadastroChanging(Nullable<global::System.DateTime> value);
        partial void OndataCadastroChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ManifestaModel", Name="situacao_nfe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class situacao_nfe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new situacao_nfe object.
        /// </summary>
        /// <param name="id_situacao">Initial value of the id_situacao property.</param>
        /// <param name="situacao">Initial value of the situacao property.</param>
        public static situacao_nfe Createsituacao_nfe(global::System.Int32 id_situacao, global::System.String situacao)
        {
            situacao_nfe situacao_nfe = new situacao_nfe();
            situacao_nfe.id_situacao = id_situacao;
            situacao_nfe.situacao = situacao;
            return situacao_nfe;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_situacao
        {
            get
            {
                return _id_situacao;
            }
            set
            {
                if (_id_situacao != value)
                {
                    Onid_situacaoChanging(value);
                    ReportPropertyChanging("id_situacao");
                    _id_situacao = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_situacao");
                    Onid_situacaoChanged();
                }
            }
        }
        private global::System.Int32 _id_situacao;
        partial void Onid_situacaoChanging(global::System.Int32 value);
        partial void Onid_situacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String situacao
        {
            get
            {
                return _situacao;
            }
            set
            {
                OnsituacaoChanging(value);
                ReportPropertyChanging("situacao");
                _situacao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("situacao");
                OnsituacaoChanged();
            }
        }
        private global::System.String _situacao;
        partial void OnsituacaoChanging(global::System.String value);
        partial void OnsituacaoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ManifestaModel", "nfe_ibfk_2", "nfe")]
        public EntityCollection<nfe> nfe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<nfe>("ManifestaModel.nfe_ibfk_2", "nfe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<nfe>("ManifestaModel.nfe_ibfk_2", "nfe", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ManifestaModel", Name="tipo_evento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tipo_evento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tipo_evento object.
        /// </summary>
        /// <param name="id_tipo">Initial value of the id_tipo property.</param>
        /// <param name="just">Initial value of the just property.</param>
        public static tipo_evento Createtipo_evento(global::System.Int32 id_tipo, global::System.Boolean just)
        {
            tipo_evento tipo_evento = new tipo_evento();
            tipo_evento.id_tipo = id_tipo;
            tipo_evento.just = just;
            return tipo_evento;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_tipo
        {
            get
            {
                return _id_tipo;
            }
            set
            {
                if (_id_tipo != value)
                {
                    Onid_tipoChanging(value);
                    ReportPropertyChanging("id_tipo");
                    _id_tipo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_tipo");
                    Onid_tipoChanged();
                }
            }
        }
        private global::System.Int32 _id_tipo;
        partial void Onid_tipoChanging(global::System.Int32 value);
        partial void Onid_tipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean just
        {
            get
            {
                return _just;
            }
            set
            {
                OnjustChanging(value);
                ReportPropertyChanging("just");
                _just = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("just");
                OnjustChanged();
            }
        }
        private global::System.Boolean _just;
        partial void OnjustChanging(global::System.Boolean value);
        partial void OnjustChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ManifestaModel", "nfe_evento_ibfk_2", "nfe_evento")]
        public EntityCollection<nfe_evento> nfe_evento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<nfe_evento>("ManifestaModel.nfe_evento_ibfk_2", "nfe_evento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<nfe_evento>("ManifestaModel.nfe_evento_ibfk_2", "nfe_evento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ManifestaModel", Name="uptabelas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class uptabelas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new uptabelas object.
        /// </summary>
        /// <param name="sequencia">Initial value of the sequencia property.</param>
        public static uptabelas Createuptabelas(global::System.Decimal sequencia)
        {
            uptabelas uptabelas = new uptabelas();
            uptabelas.sequencia = sequencia;
            return uptabelas;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal sequencia
        {
            get
            {
                return _sequencia;
            }
            set
            {
                if (_sequencia != value)
                {
                    OnsequenciaChanging(value);
                    ReportPropertyChanging("sequencia");
                    _sequencia = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sequencia");
                    OnsequenciaChanged();
                }
            }
        }
        private global::System.Decimal _sequencia;
        partial void OnsequenciaChanging(global::System.Decimal value);
        partial void OnsequenciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String local
        {
            get
            {
                return _local;
            }
            set
            {
                OnlocalChanging(value);
                ReportPropertyChanging("local");
                _local = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("local");
                OnlocalChanged();
            }
        }
        private global::System.String _local;
        partial void OnlocalChanging(global::System.String value);
        partial void OnlocalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comando
        {
            get
            {
                return _comando;
            }
            set
            {
                OncomandoChanging(value);
                ReportPropertyChanging("comando");
                _comando = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comando");
                OncomandoChanged();
            }
        }
        private global::System.String _comando;
        partial void OncomandoChanging(global::System.String value);
        partial void OncomandoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dia
        {
            get
            {
                return _dia;
            }
            set
            {
                OndiaChanging(value);
                ReportPropertyChanging("dia");
                _dia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dia");
                OndiaChanged();
            }
        }
        private Nullable<global::System.DateTime> _dia;
        partial void OndiaChanging(Nullable<global::System.DateTime> value);
        partial void OndiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hora
        {
            get
            {
                return _hora;
            }
            set
            {
                OnhoraChanging(value);
                ReportPropertyChanging("hora");
                _hora = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hora");
                OnhoraChanged();
            }
        }
        private global::System.String _hora;
        partial void OnhoraChanging(global::System.String value);
        partial void OnhoraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> priori
        {
            get
            {
                return _priori;
            }
            set
            {
                OnprioriChanging(value);
                ReportPropertyChanging("priori");
                _priori = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("priori");
                OnprioriChanged();
            }
        }
        private Nullable<global::System.Int64> _priori;
        partial void OnprioriChanging(Nullable<global::System.Int64> value);
        partial void OnprioriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();

        #endregion

    
    }

    #endregion

    
}
